default:
	rm -rf *~
clean:
	rm -rf *.out

1:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 1.cpp
2:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 2.cpp
3:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 3.cpp
4:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 4.cpp
5:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 5.cpp
6:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 6.cpp
7:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 7.cpp
8:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 8.cpp
9:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 9.cpp
10:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 10.cpp
