default:
	rm -rf *~
clean:
	rm -rf *.out

3004:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 3004.cpp
1:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 1.cpp
2:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 2.cpp
3:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 3.cpp
4:
	g++ -std=gnu++11 -O2 -g -Wall -Werror -DSAAD 4.cpp
